
import Dashboard from "./components/Dashboard";
import { LoaderFunction } from "@remix-run/node";

const allProjects = [
  {
    id: 1,
    name: "Translation Guide.docx",
    status: "Failure",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 2,
    name: "Tibetan Grammar.pdf",
    status: "Failure",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "40%",
    errorMsg:
      'Traceback (most recent call last):\nFile "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable\nreturn callable_(*args, **kwargs)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__\nreturn _end_unary_response_blocking(state, call, False, None)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\nraise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\nstatus = StatusCode.PERMISSION_DENIED\ndetails = "This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."\ndebug_error_string = "UNKNOWN:Error received from peer ipv4:172.253.122.95:443 {created_time:"2023-04-03T14:54:27.961132905+05:30", grpc_status:7, grpc_message:"This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."}"\n>',
  },
  {
    id: 3,
    name: "Buddhist Texts.docx",
    status: "Success",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 4,
    name: "Manuscript_Analysis.pdf",
    status: "Success",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 5,
    name: "Cultural_Research.docx",
    status: "Failure",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "40%",
    errorMsg:
      'Traceback (most recent call last):\nFile "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable\nreturn callable_(*args, **kwargs)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__\nreturn _end_unary_response_blocking(state, call, False, None)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\nraise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\nstatus = StatusCode.PERMISSION_DENIED\ndetails = "This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."\ndebug_error_string = "UNKNOWN:Error received from peer ipv4:172.253.122.95:443 {created_time:"2023-04-03T14:54:27.961132905+05:30", grpc_status:7, grpc_message:"This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."}"\n>',
  },
  {
    id: 6,
    name: "Historical_Documents.docx",
    status: "Success",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 7,
    name: "Ancient_Scripts.pdf",
    status: "Failure",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "40%",
    errorMsg:
      'Traceback (most recent call last):\nFile "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable\nreturn callable_(*args, **kwargs)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__\nreturn _end_unary_response_blocking(state, call, False, None)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\nraise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\nstatus = StatusCode.PERMISSION_DENIED\ndetails = "This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."\ndebug_error_string = "UNKNOWN:Error received from peer ipv4:172.253.122.95:443 {created_time:"2023-04-03T14:54:27.961132905+05:30", grpc_status:7, grpc_message:"This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."}"\n>',
  },
  {
    id: 8,
    name: "Monlam_TTS_Overview.docx",
    status: "Success",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 9,
    name: "Language_Model_Notes.docx",
    status: "Success",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 10,
    name: "OCR_Training_Data.docx",
    status: "Success",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 11,
    name: "Speech_Recognition_Guide.pdf",
    status: "Failure",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "40%",
    errorMsg:
      'Traceback (most recent call last):\nFile "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable\nreturn callable_(*args, **kwargs)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__\nreturn _end_unary_response_blocking(state, call, False, None)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\nraise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\nstatus = StatusCode.PERMISSION_DENIED\ndetails = "This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."\ndebug_error_string = "UNKNOWN:Error received from peer ipv4:172.253.122.95:443 {created_time:"2023-04-03T14:54:27.961132905+05:30", grpc_status:7, grpc_message:"This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."}"\n>',
  },
  {
    id: 12,
    name: "Tibetan_Fonts_Analysis.docx",
    status: "Success",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 13,
    name: "Pecha_Alignment_Report.pdf",
    status: "Success",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 14,
    name: "Bilingual_Glossary.docx",
    status: "Failure",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "40%",
    errorMsg:
      'Traceback (most recent call last):\nFile "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable\nreturn callable_(*args, **kwargs)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__\nreturn _end_unary_response_blocking(state, call, False, None)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\nraise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\nstatus = StatusCode.PERMISSION_DENIED\ndetails = "This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."\ndebug_error_string = "UNKNOWN:Error received from peer ipv4:172.253.122.95:443 {created_time:"2023-04-03T14:54:27.961132905+05:30", grpc_status:7, grpc_message:"This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."}"\n>',
  },
  {
    id: 15,
    name: "AI_Linguistics_Study.docx",
    status: "Success",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 16,
    name: "Phonetics_Research.pdf",
    status: "Success",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 17,
    name: "Syntax_Study_2023.docx",
    status: "Failure",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "40%",
    errorMsg:
      'Traceback (most recent call last):\nFile "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable\nreturn callable_(*args, **kwargs)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__\nreturn _end_unary_response_blocking(state, call, False, None)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\nraise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\nstatus = StatusCode.PERMISSION_DENIED\ndetails = "This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."\ndebug_error_string = "UNKNOWN:Error received from peer ipv4:172.253.122.95:443 {created_time:"2023-04-03T14:54:27.961132905+05:30", grpc_status:7, grpc_message:"This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."}"\n>',
  },
  {
    id: 18,
    name: "Machine_Translation_Results.pdf",
    status: "Success",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 19,
    name: "Semantic_Model_Notes.docx",
    status: "Success",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "100%",
  },
  {
    id: 20,
    name: "Training_Log_2024.pdf",
    status: "Failure",
    projectName: "Project Alpha",
    lineSegmentationModel: "Model v1.0",
    characterRecognitionModel: "OCR v2.1",
    startDate: "2024-01-01",
    completDate: "2024-01-13",
    progress: "40%",
    errorMsg:
      'Traceback (most recent call last):\nFile "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable\nreturn callable_(*args, **kwargs)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__\nreturn _end_unary_response_blocking(state, call, False, None)\nFile "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\nraise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\nstatus = StatusCode.PERMISSION_DENIED\ndetails = "This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."\ndebug_error_string = "UNKNOWN:Error received from peer ipv4:172.253.122.95:443 {created_time:"2023-04-03T14:54:27.961132905+05:30", grpc_status:7, grpc_message:"This API method requires billing to be enabled. Please enable billing on project #373802399616 by visiting https://console.developers.google.com/billing/enable?project=373802399616 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry."}"\n>',
  },
];


export const loader:LoaderFunction = async ({request}) => {
  const searchQuery = new URL(request.url).searchParams.get("search") || "";
  const filteredProjects = allProjects.filter((project) =>
    project.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return {
    filteredProjects,
    totalProjects: filteredProjects.length,
  };
};

export default function route() {
  return <Dashboard />
}
